GROQ_API_KEY = "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"
[postgres]
host = "db.wpactrrgxmitgregzbiq.supabase.co"
database = "postgres"
user = "postgres"
password = "Roshan123"
port = "5432"
